### ISSUE TITLE
[HELP] Adding new words

### ISSUE THREAD

**Issue by Cicorione** [priner/micro-aspell-plugin#12]
Hi Priner,

thank you very much for this plugin is really useful.

I love using micro for writing my blog however I am not a coder and I couldn't figuring out what this means:

`lua:aspell.addpersonal `

Could you help me with a real example as you did to explain other features of your plugin?

Thanks in advance and sorry for dumb question!

Cicorione

**Comment by priner** [comment]
As an example you can run this command `bind Ctrl-p lua:aspell.addpersonal` to bind Ctrl P to the addpersonal action.
So that when you hit Ctrl P it will add the word your cursor is on to your personal dictionary (it's probably in $HOME/.aspell.en.pws  (or not en, that depends on the language) if you want to inspect it manually or remove something from there).

I personally didn't bind it to anything cause I don't use it that frequently, so I just type the `addpersonal` command when I need it which does the same thing.

**Comment by Cicorione** [comment]
Nice, thank you very much!

Perhaps you don't use it frequently but I do daily, and your plugin for me is really the best!

I really like Micro but also because your plug-in, thanks again!

**Comment by Cicorione** [comment]
WOW!!! Astonishing!

I haven't really what gem you gave on my hands until I tried it!

You really made my day! 👏👏👏
